export const CATS = {
  "Groceries":     { emoji: "🛒", color: "#4ade80" },
  "Dining":        { emoji: "🍽️", color: "#fb923c" },
  "Fast Food":     { emoji: "🍔", color: "#f87171" },
  "Coffee":        { emoji: "☕", color: "#d97706" },
  "Alcohol":       { emoji: "🍺", color: "#fbbf24" },
  "Rent":          { emoji: "🔑", color: "#818cf8" },
  "Housing":       { emoji: "🏠", color: "#60a5fa" },
  "Mortgage":      { emoji: "🏦", color: "#3b82f6" },
  "Utilities":     { emoji: "💡", color: "#22d3ee" },
  "Internet":      { emoji: "🌐", color: "#38bdf8" },
  "Phone":         { emoji: "📞", color: "#a78bfa" },
  "Transport":     { emoji: "🚗", color: "#facc15" },
  "Gas":           { emoji: "⛽", color: "#fcd34d" },
  "Parking":       { emoji: "🅿️", color: "#94a3b8" },
  "Taxi / Uber":   { emoji: "🚕", color: "#fde68a" },
  "Flights":       { emoji: "🛫", color: "#7dd3fc" },
  "Hotel":         { emoji: "🏨", color: "#67e8f9" },
  "Travel":        { emoji: "✈️", color: "#34d399" },
  "Healthcare":    { emoji: "💊", color: "#f87171" },
  "Pharmacy":      { emoji: "💉", color: "#fb7185" },
  "Dentist":       { emoji: "🦷", color: "#e2e8f0" },
  "Gym":           { emoji: "🏋️", color: "#86efac" },
  "Sports":        { emoji: "⚽", color: "#6ee7b7" },
  "Outdoor":       { emoji: "🏕️", color: "#84cc16" },
  "Electronics":   { emoji: "📱", color: "#38bdf8" },
  "Clothing":      { emoji: "👕", color: "#c084fc" },
  "Shoes":         { emoji: "👟", color: "#a78bfa" },
  "Accessories":   { emoji: "👜", color: "#f0abfc" },
  "Beauty":        { emoji: "💄", color: "#f472b6" },
  "Skincare":      { emoji: "🧴", color: "#e879f9" },
  "Haircare":      { emoji: "✂️", color: "#d946ef" },
  "Shopping":      { emoji: "🛍️", color: "#c084fc" },
  "Home & Garden": { emoji: "🛋️", color: "#a3e635" },
  "Furniture":     { emoji: "🪑", color: "#a8a29e" },
  "Cleaning":      { emoji: "🧹", color: "#67e8f9" },
  "Pets":          { emoji: "🐾", color: "#fb923c" },
  "Kids":          { emoji: "🧸", color: "#fda4af" },
  "Baby":          { emoji: "👶", color: "#fbcfe8" },
  "Education":     { emoji: "📚", color: "#fcd34d" },
  "Books":         { emoji: "📖", color: "#fbbf24" },
  "Streaming":     { emoji: "📺", color: "#c084fc" },
  "Gaming":        { emoji: "🎮", color: "#818cf8" },
  "Entertainment": { emoji: "🎬", color: "#f472b6" },
  "Subscriptions": { emoji: "🔁", color: "#a78bfa" },
  "Office":        { emoji: "🖥️", color: "#94a3b8" },
  "Gifts":         { emoji: "🎁", color: "#fb7185" },
  "Charity":       { emoji: "❤️",  color: "#f87171" },
  "Insurance":     { emoji: "🛡️", color: "#64748b" },
  "Taxes":         { emoji: "🧾", color: "#94a3b8" },
  "Other":         { emoji: "📌", color: "#6b7280" },
};

export const CAT_NAMES = Object.keys(CATS);
